#!/bin/sh

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh

juju-log "$JUJU_REMOTE_UNIT departed"

sed -i s/^rts\.storm\.webserv.*/rts\.storm\.webserv\:\ NODEJS_APP_URL\:NODEJS_APP_PORT\/NODEJS_APP_URI/ ${CONFIG_FILE}

${HOME}/hooks/stop

exit 0
