#!/bin/sh

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh

juju-log "$JUJU_REMOTE_UNIT joined"

NODEJS_APP_URL=`relation-get private-address $JUJU_REMOTE_UNIT`
NODEJS_APP_PORT=`relation-get port $JUJU_REMOTE_UNIT`

if [ -z "${NODEJS_APP_URL}"  ] || [ -z "${NODEJS_APP_PORT}"  ] ; then
    exit 0
fi

sed -i s/^rts\.storm\.webserv.*/rts\.storm\.webserv\:\ http\:\/\/"${NODEJS_APP_URL}"\:${NODEJS_APP_PORT}\/"${NODEJS_APP_URI}"/ ${CONFIG_FILE}

${HOME}/hooks/config-changed

exit 0
