#!/bin/bash

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh

XFACTOR=`cat .current_topology | head -n1`

STATUS="`storm list | grep 'No topologies running.' | wc -l`"

if [ "${STATUS}" = "1" ] ; then
    juju-log "No Topologies running. Exiting gracefully"
    exit 0
fi


juju-log "Killing topology sentiment-analysis-${XFACTOR}..."
storm kill "sentiment-analysis-${XFACTOR}"

sleep 3
exit 0

